### PR TITLE
blank import to call init function of boltdb/memdb.

### PR DESCRIPTION
**Pull request by FGtatsuroWork**
init functions register these store type in gateway. In develop HEAD, it seems that init functions of store type aren't called.

```
(py2.7)KiiPlatform/gateway-agent - [develop] » make build-debug
go build -o gwagent-debug -tags "debug"
(py2.7)KiiPlatform/gateway-agent - [develop] » ./gwagent-debug
DEBUG 2016/02/09 19:46:26 Config: config.Config{Gateway:config.Gateway{VendorThingID:"qatestvendor1", ThingPassword:"thingpassword", ThingType:"GATEWAY", ThingProperties:map[string]interface {}{"_firmware_version":"1.0.0", "_vendor":"Kii", "_lot":"S2001512081200G0012340001"}}, Admin:config.User{Username:"admin_user", Password:"admin_pass"}, MasterApp:config.MasterApp{App:config.App{Site:"development_jp", AppID:"a6d18eef", AppKey:"9b0c37d275dab4aa7818c76c296b0b45"}, EndnodeAppsBackupBucket:"endnodeApps"}, Sites:map[string]string{"us":"https://api.kii.com", "development_jp":"https://api-development-jp.internal.kii.com", "jp":"https://api-jp.kii.com", "cn":"https://api-cn3.kii.com", "sg":"https://api-sg.kii.com"}, Store:config.Store{Type:"memory", Params:map[string]interface {}{"filename":"gwagent.db", "capacity":100}}, Mqtt:config.Mqtt{KeepAlive:300, LocalBroker:config.Addr{Host:"127.0.0.1", Port:1883}, LocalClientID:"gateway-agent-endnode-mqtt"}, LocalServer:struct { Addr config.Addr "yaml:\"addr\"" }{Addr:config.Addr{Host:"127.0.0.1", Port:4001}}}
2016/02/09 19:46:26 unknown store factory: memory
```

### CODE REVIEW

**Comment by FGtatsuroWork** [comment]
On CircleCI, `go build -v` is failed.

**Comment by yongpingchen** [comment]
please try `build without cache` on circleCI first.

**Comment by FGtatsuroWork** [comment]
@yongpingchen 
Thank you for your comment! I'll do so in next time.

**Comment by yongpingchen** [comment]
Welcome. If it still fail, after rebuild without cache, it means real bugs :)

**Comment by taro-m** [comment]
I have moved those blank imports into separated files.

And added comments which goimports claims "need comment for each blank imports" like.

**Comment by taro-m** [comment]
thx! :+1:

**Pull request merged**
