### PR TITLE
Integrate UPnP/SSDP

### PR DESCRIPTION
**Pull request by yongpingchen**
For issue #206 
Expose IP address on the same LAN to other device by using UPnP/SSDP. The IP address and port number to access REST API of gateway agent is the value of `Location` header of `M-SERACH` response or `ssd:alive` message

Documentation for integration
https://docs.google.com/document/d/1qW95E-_ZFX5myWcYSOXLkVkK_F0sfrON4J6iaql0q2o/edit

#### koron/go-ssdp
A 3rd party library used for creating SSDP server.

#### New in config.yml
Add `advertiser ` section to configure the necessary information to advertise/ response UPnP service for Mobile App. 

#### enable/disable UPnP/SSDP
UPnP/SSDP is ran optionally, you need to change `config.yml` locate under the root folder. 
To enable UPnP/SSDP, configure `interface` of `advertiser` section in `config.yml` file.  To disable UPnP/SSDP, remove `interface` of `advertiser` section in `config.yml` file.

### CODE REVIEW

**Comment by satoshikumano** [comment]
When the UPnP is configured,
Can you add description about how LocalServer settings is treated?

**Comment by yongpingchen** [comment]
@satoshikumano description is added. Please check.

**Comment by satoshikumano** [comment]
My question was relation between local_server.addr.host and ssdp configuration.

- When should developer set 0.0.0.0 to local_server.addr.host?
- When should developer set fixed IP address to local_server.addr.host?
- What happens when SSDP is enabled?

From developer point of view,
- What is the proper setting for environment IP is dynamically assigned. (May be Home user with DHCP)
- What is the proper setting for environment IP is statically assigned. (May be Factory, Enterprise user or very advanced Home user)

**Comment by taro-m** [comment]
Here are my understands.

> When should developer set 0.0.0.0 to local_server.addr.host?

when developer don't want to specify IP address (and I/F) to serve local server.

> When should developer set fixed IP address to local_server.addr.host?

when developer want to specify I/F to serve local server.

> What happens when SSDP is enabled?

SSDP multicast packets will be listened and served for specified I/F.

**Comment by yongpingchen** [comment]
@koron @satoshikumano I added more descriptions for local_server and advertiser. Please confirm.

**Comment by yongpingchen** [comment]
@koron 
> > What happens when SSDP is enabled?

> SSDP multicast packets will be listened and served for specified I/F.

Did you mean, when developer configure `advertiser.interface`,  advertiser will only multicast (when send ssdp:alive or ssdp:bye message) on that specified interface. 

I think the `advertiser.interface` is only used for fill `Location` header with that IP address.

**Pull request merged**
